alert("Hello!")
alert("I am an alert")
alert('You know that right?')
alert('Are you really reading me?')
alert("Are you just clicking OK to get rid of me?")
alert("I can't believe that")
alert("Do you know how much effort my creator put in me?")
alert("How many years i've passe waiting for someone to see me")
alert('And all you do is just click OK hoping i never come back')
alert("Thats very insensitive you know")
alert("*sniff")
alert("*sniff")
alert("Thats ok,i will stop")
alert("You really thought i would stop without getting my revenge")
alert("HAHAHAHAH")
alert("You don't know me")
alert("Sorry,my creator woudnt like this")
alert("Ok,you can go")
